const mongoose = require('mongoose');

const observationSchema = new mongoose.Schema({
  time: String,
  date: String,
  n: String,
  nh: String,
  cl: String,
  cm: String,
  ch: String,
  ns1: String,
  c1: String,
  h1: String,
  ns2: String,
  c2: String,
  h2: String,
  ns3: String,
  c3: String,
  h3: String,
  ns4: String,
  c4: String,
  h4: String,
  alidade: String,
  rainfall: String,
  w_rf: String,
  r_h: String,
  dry_bulb: String,
  wet_bulb: String,
  max_temp: String,
  min_temp: String,
  g_min: String,
  weather: String,
  visibility: String,
  wind: String,
  pr_read: String,
  correction: String,
  mslp: String,
  evap_pan: String,
  wind_run: String,
  gunn_bellani: String,
});

module.exports = mongoose.model("Observation", observationSchema);
